{
 "title": "AxoSyslog",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Input Events (rate)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(syslogng_input_events_total[2m])) by (cluster, namespace, pod)",
     "legendFormat": "{{cluster}}/{{namespace}}/{{pod}}"
    }
   ]
  },
  {
   "title": "Output Events (rate)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(syslogng_output_events_total[2m])) by (driver_instance, result)",
     "legendFormat": "{{driver_instance}} => {{result}}"
    }
   ]
  },
  {
   "title": "Log Ratio of Pods",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(syslogng_input_events_total) by (cluster, namespace, pod)",
     "legendFormat": "{{cluster}}/{{namespace}}/{{pod}}"
    }
   ]
  },
  {
   "title": "Log by Pod (total)",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "sum(syslogng_input_events_total) by (cluster, namespace, pod)",
     "legendFormat": "{{cluster}}/{{namespace}}/{{pod}}"
    }
   ]
  }
 ]
}